env: dev
name: "thorpesystems.com"
description: "Another developers blog"
url: "http://localhost:7000"
twitter: tonyrq
github: trq
username: "Tony Quilkey"
#gravatar_url: https://1.gravatar.com/avatar/baf2401c60cebda2259c84ef825569f6
